[package]
description = "Cube Infinifold (A Puzzle Game)"
name = "cube-infinifold"
version = "0.1.1"
edition = "2021"
authors = ["Yijun Wu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "1.4", features = ["enable-glwindow"] }
glu-sys = "0.1.4"
glow = "0.13"

[build-dependencies]
winresource = "0.1"


[package.metadata.winresource]
OriginalFilename = "Cube Infinifold.exe"
LegalCopyright = "Infinifold © 2024"
# FileDescription = "Cube Infinifold (A Puzzle indie Game)"
ProductName = "Cube Infinifold"
# ProductVersion = "0.1.1.1"

