[package]
name = "test_set_env"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test_set_env"
path = "src/bin/main.rs"

[lib]
name = "add"
path = "src/lib/add.rs"
crate-type = ["dylib"]


[dependencies]
libloading = "*"