[package]
name = "test_set_env"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "start"
path = "src/main.rs"


# [lib]
[[bin]]
name = "main"
path = "src/lib.rs"
# crate-type = ["dylib"]


[lib]
name = "add"
path = "src/add.rs"
crate-type = ["dylib"]


[dependencies]
libloading = "*"