name: Build Only

on:
  workflow_dispatch:
  push:

env:
  EXECUTABLE_NAME: cube-infinifold
  EXECUTABLE_CHECK_NAME: cube-infinifold-check
  ENABLE_CARGO_TEST: false
  ENABLE_CARGO_BUILD: false
  ENABLE_PROGRAM_CHECK: false

jobs:
  build_on_ubunutu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      # Set up ffmpeg environment
      - name: Install dependencies
        run: |
          sudo apt install -y --no-install-recommends clang curl pkg-config
          sudo apt install libavcodec-dev libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev
      # Install rust toolchain
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      # Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      # Build the project
      - name: Build Project
        if: ${{ env.ENABLE_CARGO_BUILD }}
        run: cargo build --verbose --release
      # Create binary file if not building
      - name: Create Binary
        if: ${{ !env.ENABLE_CARGO_BUILD }}
        run: |
          mkdir -p ./target/release
          touch ./target/release/${{ env.EXECUTABLE_NAME }}
          touch ./target/release/${{ env.EXECUTABLE_CHECK_NAME }}
      # List the files in the target/release directory
      - name: List Files
        run: |
          ls /usr/lib/*.so
          ls ./target/release
      # Run the tests
      - name: Cargo Test
        if: ${{ env.ENABLE_CARGO_TEST }}
        run: cargo test
      # copy and compress the binary and library into a zip file
      - name: Copy and Compress Binary
        run: |
          cd ./target/release
          mkdir -p temp_files/libs
          mv ${{ env.EXECUTABLE_NAME }} temp_files/
          mv *.so temp_files/libs/
          cd temp_files
          zip -r ../${{ env.EXECUTABLE_NAME }}_ubuntu.zip .
          cd ..
          mv ${{ env.EXECUTABLE_CHECK_NAME }} temp_files/
          cd ..
          cd ..
      # Test the Rust program
      - name: Run Rust program
        if: ${{ env.ENABLE_PROGRAM_CHECK }}
        run: |
          ./${{ env.EXECUTABLE_CHECK_NAME }}
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Rust program failed with exit code $exit_code"
            exit 1
          fi
        working-directory: ./target/release/temp_files
      # delete the temp_files directory
      - name: Delete temp_files
        run: |
          rm -rf ./target/release/temp_files
      # then upload the zip to the release
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.get_counter_and_release.outputs.upload_url }}
          asset_path: ./target/release/${{ env.EXECUTABLE_NAME }}_ubuntu.zip
          asset_name: ${{ env.EXECUTABLE_NAME }}_ubuntu.zip
          asset_content_type: application/zip

  build_on_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      # Set up ffmpeg environment
      - name: Install dependencies
        run: |
          $VCINSTALLDIR = $(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath)
          Add-Content $env:GITHUB_ENV "LIBCLANG_PATH=${VCINSTALLDIR}\VC\Tools\LLVM\x64\bin`n"
          Invoke-WebRequest "${env:FFMPEG_DOWNLOAD_URL}" -OutFile ffmpeg-release-full-shared.7z
          7z x ffmpeg-release-full-shared.7z
          mkdir ffmpeg
          mv ffmpeg-*/* ffmpeg/
          Add-Content $env:GITHUB_ENV "FFMPEG_DIR=${pwd}\ffmpeg`n"
          Add-Content $env:GITHUB_PATH "${pwd}\ffmpeg\bin`n"
        env:
          FFMPEG_DOWNLOAD_URL: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z
      # Install rust toolchain
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      # Build the project
      - name: Build Project
        if: ${{ env.ENABLE_CARGO_BUILD }}
        run: cargo build --release
      # Create binary file if not building
      - name: Create Binary
        if: ${{ !env.ENABLE_CARGO_BUILD }}
        run: |
          mkdir -p ./target/release
          echo. > ./target/release/${{ env.EXECUTABLE_NAME }}.exe
          echo. > ./target/release/${{ env.EXECUTABLE_CHECK_NAME }}.exe
      # Cargo Test
      - name: Cargo Test
        if: ${{ env.ENABLE_CARGO_TEST }}
        run: cargo test
      # List the files in the target/release directory
      - name: List Files
        run: |
          ls ${pwd}/ffmpeg/bin/*.dll
          ls ./target/release
      # copy and compress the binary and library into a zip file
      - name: Copy and Compress Binary
        run: |
          cd ./target/release
          mkdir -p ${{ env.EXECUTABLE_NAME }}_windows/libs
          mv ${{ env.EXECUTABLE_NAME }}.exe ${{ env.EXECUTABLE_NAME }}_windows/
          mv *.dll ${{ env.EXECUTABLE_NAME }}_windows/libs/
          Compress-Archive -Path "${{ env.EXECUTABLE_NAME }}_windows" ${{ env.EXECUTABLE_NAME }}_windows.zip
          mv ${{ env.EXECUTABLE_CHECK_NAME }}.exe ${{ env.EXECUTABLE_NAME }}_windows/
          cd ..
          cd ..
      # Test the Rust program
      - name: Run Rust program
        if: ${{ env.ENABLE_PROGRAM_CHECK }}
        run: |
          ./${{ env.EXECUTABLE_CHECK_NAME }}.exe
          $exit_code = $LASTEXITCODE
          if ($exit_code -ne 0) {
            Write-Output "Rust program failed with exit code $exit_code"
            exit 1
          }
        working-directory: ./target/release/${{ env.EXECUTABLE_NAME }}_windows
      # delete the cube-infinifold_windows directory
      - name: Delete cube-infinifold_windows
        run: |
          Remove-Item -Path "./target/release/${{ env.EXECUTABLE_NAME }}_windows" -Recurse -Force
      # then upload the zip to the release
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.get_counter_and_release.outputs.upload_url }}
          asset_path: ./target/release/${{ env.EXECUTABLE_NAME }}_windows.zip
          asset_name: ${{ env.EXECUTABLE_NAME }}_windows.zip
          asset_content_type: application/zip

  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      # Set up ffmpeg environment
      - name: Install dependencies
        run: brew install ffmpeg pkg-config
      # Install rust toolchain
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      # Build the project
      - name: Build Project
        if: ${{ env.ENABLE_CARGO_BUILD }}
        run: cargo build --verbose --release
      # Create binary file if not building
      - name: Create Binary
        if: ${{ !env.ENABLE_CARGO_BUILD }}
        run: |
          mkdir -p ./target/release
          touch ./target/release/${{ env.EXECUTABLE_NAME }}
          touch ./target/release/${{ env.EXECUTABLE_CHECK_NAME }}
      # Cargo Test
      - name: Cargo Test
        if: ${{ env.ENABLE_CARGO_TEST }}
        run: cargo test
      # List the files in the target/release directory
      - name: List Files
        run: |
          ffmpeg_path=$(brew --prefix ffmpeg)
          cp $ffmpeg_path/lib/*.dylib ./target/release
          ls ./target/release
      # copy and compress the binary and library into a zip file
      - name: Copy and Compress Binary
        run: |
          cd ./target/release
          mkdir -p temp_files/libs
          cp ${{ env.EXECUTABLE_NAME }} temp_files/
          cp *.dylib temp_files/libs/
          cd temp_files
          zip -r ../${{ env.EXECUTABLE_NAME }}_macos.zip .
          cd ..
          mv ${{ env.EXECUTABLE_CHECK_NAME }} temp_files/
          cd ..
          cd ..
      # Test the Rust program
      - name: Run Rust program
        if: ${{ env.ENABLE_PROGRAM_CHECK }}
        run: |
          ./${{ env.EXECUTABLE_CHECK_NAME }}
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Rust program failed with exit code $exit_code"
            exit 1
          fi
        working-directory: ./target/release/temp_files
      # delete the temp_files directory
      - name: Delete temp_files
        run: |
          rm -rf ./target/release/temp_files
      # then upload the zip to the release
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.get_counter_and_release.outputs.upload_url }}
          asset_path: ./target/release/${{ env.EXECUTABLE_NAME }}_macos.zip
          asset_name: ${{ env.EXECUTABLE_NAME }}_macos.zip
          asset_content_type: application/zip
