name: Rust

## manuallyon:
on:
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Config ffmpeg
      run: pacman -Sy mingw-w64-x86_64-pkg-config mingw-w64-x86_64-gcc mingw-w64-x86_64-ffmpeg
    - name: Build
      run: cargo build --verbose --release
