name: Rust

## manuallyon:
on:
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: FedericoCarboni/setup-ffmpeg@v3
      id: setup-ffmpeg
      with:
        ffmpeg-version: release
        architecture: ''
        linking-type: static
        github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
    - name: Build
      run: cargo build --verbose --release
