name: Rust

## manuallyon:
on:
  workflow_dispatch:
    inputs:
      input:
        description: "Build and Release cargo build"
        required: false
        default: "Master"
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg:4.4-ubuntu
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt update
        apt install -y --no-install-recommends clang curl pkg-config
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      # with:
      #   toolchain: stable
      #   override: true
      #   components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose --release
