name: Rust

## manuallyon:
on:
  workflow_dispatch:
    inputs:
      input:
        description: "Build and Release cargo build"
        required: false
        default: "Master"
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-on-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
