name: Simple Test Only

on:
  workflow_dispatch:
  push:

jobs:
  # test_linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@main
  #     - run: |
  #         cd ./examples/install_dependencies
  #         cargo build
  #         cd ../../target/debug
  #         mkdir libs
  #         ./install_dependencies
  #         ffmpeg -version
  # test_mac:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@main
  #     - run: |
  #         cd ./examples/install_dependencies
  #         cargo build
  #         cd ../../target/debug
  #         mkdir libs
  #         ./install_dependencies
  #         ffmpeg -version
          
  test_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      - run: |
          cd ./examples/install_dependencies
          cargo build
          cd ../../target/debug
          mkdir libs
          ./install_dependencies.exe

          # # this may not work, depending on system
          # # see: https://github.com/microsoft/winget-pkgs/issues/95349
          # ffmpeg -veersion

      - run: |
          cd ./tools/ffmpeg-loader/
          cargo test

      - uses: actions/upload-artifact@main
        with:
          name: test_video
          path: ./target/debug/deps/*.mp4 


  # test_winget:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Install winget
  #       uses: Cyberboss/install-winget@v1
  #     - run: winget install --id=Gyan.FFmpeg -e --accept-package-agreements --accept-source-agreements
