name: Simple Test Only

on:
  workflow_dispatch:
  push:

jobs:
  # test_linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@main
  #     - run: |
  #         cd ./examples/install_dependencies
  #         cargo build
  #         cd ../../target/debug
  #         mkdir libs
  #         ./install_dependencies
  #         ffmpeg -version
  # test_mac:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@main
  #     - run: |
  #         cd ./examples/install_dependencies
  #         cargo build
  #         cd ../../target/debug
  #         mkdir libs
  #         ./install_dependencies
  #         ffmpeg -version
          
  # test_win:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@main
  #     - run: |
  #         cd ./examples/install_dependencies
  #         cargo build
  #         cd ../../target/debug
  #         mkdir libs
  #         ./install_dependencies.exe
  #         ffmpeg -version


  test_winget:
    runs-on: windows-latest
    steps:
      - name: Install winget
        # uses: Cyberboss/install-winget@v1
        run: |
          $progressPreference = 'silentlyContinue'
          Write-Information "Downloading WinGet and its dependencies..."
          Invoke-WebRequest -Uri https://aka.ms/getwinget -OutFile Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
          Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx
          Invoke-WebRequest -Uri https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.8.6/Microsoft.UI.Xaml.2.8.x64.appx -OutFile Microsoft.UI.Xaml.2.8.x64.appx
          Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx
          Add-AppxPackage Microsoft.UI.Xaml.2.8.x64.appx
          Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
      - run: winget install --id=Gyan.FFmpeg -e --accept-package-agreements --accept-source-agreements
      # - run: scoop install ffmpeg
