name: Build Only Using Matrix

on:
  workflow_dispatch:
  push:

jobs:
  build_and_release:
    runs-on: ${{ matrix.os.system }}-latest
    continue-on-error: true
    strategy:
      matrix:
        os: 
          - name: 'Build on Windows'
            system: 'windows'
            # build_command: ./tools/build/build.ps1
            ext: '.exe'
            libname: 'add.dll'
          - name: 'Build on Linux'
            system: 'ubuntu'
            # build_command: sh ./tools/build/build.sh
            libname: 'libadd.so'
          - name: 'Build on MacOS'
            system: 'macos'
            # build_command: sh ./tools/build/build.sh
            libname: 'libadd.dylib'
            
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          # cd ./examples/test_set_env
          cargo build
        working-directory: ./examples/test_set_env
      - name: Test
        run: |
          ls
          cd ./target/debug
          mkdir -p ./libs
          cp ${{ matrix.os.libname }} ./libs

          ./test_set_env${{ matrix.os.ext }}

          rm ${{ matrix.os.libname }}

          ./test_set_env${{ matrix.os.ext }}
          