name: Simple Test Only

on:
  workflow_dispatch:
  push:

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install ffmpeg
          ffmpeg -version=4.4.2
          version_number=$(ffmpeg -version | grep 'ffmpeg version' | cut -d ' ' -f 3)
          echo "ffmpeg version: $version_number"


