name: Build Selected Test Only

on:
  workflow_dispatch:
  push:

jobs:
  build_and_release:
    runs-on: ${{ matrix.os.system }}-latest
    continue-on-error: true
    strategy:
      matrix:
        os: 
          # - name: 'Build on Windows'
          #   system: 'windows'
          #   # build_command: ./tools/build/build.ps1
          #   ext: '.exe'
          #   libname: 'add.dll'
          #   libname2: 'sublib.dll'
          - name: 'Build on Linux'
            system: 'ubuntu'
            # build_command: sh ./tools/build/build.sh
            libname: 'libadd.so'
            libname2: 'libsublib.so'
            sudo: sudo
          # - name: 'Build on MacOS'
          #   system: 'macos'
          #   # build_command: sh ./tools/build/build.sh
          #   libname: 'libadd.dylib'
          #   libname2: 'libsublib.dylib'
            
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: cargo build
        working-directory: ./examples/test_set_env
      - name: Build
        run: cargo build
        working-directory: ./examples/test_example_lib
      - name: Test
        continue-on-error: true
        run: |
          cd ./target/debug

          mkdir -p ./libs
          cp ${{ matrix.os.libname }} ./libs
          cp ${{ matrix.os.libname2 }} ./libs

          ls
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/runner/work/Cube-Infinifold/Cube-Infinifold/target/debug/libs
          ${{ matrix.os.sudo }} ./test_set_env${{ matrix.os.ext }}


      # - name: Test
      #   run: |
      #     # export PATH=$PATH:/home/runner/work/Cube-Infinifold/Cube-Infinifold/target/debug/libs
      #     # export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/runner/work/Cube-Infinifold/Cube-Infinifold/target/debug/libs
      #     cd ./target/debug

      #     mkdir -p ./libs
      #     cp ${{ matrix.os.libname }} ./libs

      #     ls
      #     ./test_set_env${{ matrix.os.ext }}

      #     rm ${{ matrix.os.libname }}

      #     ./test_set_env${{ matrix.os.ext }}
          