name: Simple Test Only

on:
  workflow_dispatch:
  push:

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd ./examples/install_dependencies
          cargo run


